from __future__ import annotations

import argparse
import csv
from pathlib import Path
import random
import tempfile

from generate_muon_scan import (
    build_visualization_lines,
    format_position_line,
    load_gdml_variables,
    load_template_lines,
)


DEFAULT_NUM_EVENTS = 1000
DEFAULT_SEED = 20260504


def build_random_positions(
    num_events: int, slab_half_xy: float, source_y: float, seed: int
) -> list[tuple[float, float, float]]:
    rng = random.Random(seed)
    return [
        (
            rng.uniform(-slab_half_xy, slab_half_xy),
            source_y,
            rng.uniform(-slab_half_xy, slab_half_xy),
        )
        for _ in range(num_events)
    ]


def build_header_comments(num_events: int, seed: int) -> list[str]:
    return [
        "# Random muon scan generated by generate_random_muon_scan.py",
        f"# Total random single-muon events: {num_events}",
        f"# Random seed: {seed}",
        "# Positions are sampled uniformly over x,z on the slab top face.",
        "# Truth labels are written to random_muon_scan_positions.csv.",
    ]


def write_positions_csv(
    output_path: Path, positions: list[tuple[float, float, float]], unit: str
) -> None:
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", newline="", dir=output_path.parent, delete=False
    ) as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "event_id",
                "run_id",
                "x",
                "y",
                "z",
                "unit",
                "true_x_cm",
                "true_y_cm",
                "true_z_cm",
            ],
        )
        writer.writeheader()
        for event_id, (x, y, z) in enumerate(positions):
            writer.writerow(
                {
                    "event_id": event_id,
                    "run_id": event_id,
                    "x": f"{x:.6f}",
                    "y": f"{y:.6f}",
                    "z": f"{z:.6f}",
                    "unit": unit,
                    "true_x_cm": f"{x:.6f}" if unit == "cm" else "",
                    "true_y_cm": f"{y:.6f}" if unit == "cm" else "",
                    "true_z_cm": f"{z:.6f}" if unit == "cm" else "",
                }
            )
        temp_path = Path(handle.name)
    temp_path.replace(output_path)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate random single-muon GPS positions over the slab top face."
    )
    parser.add_argument(
        "num_events",
        nargs="?",
        type=int,
        default=DEFAULT_NUM_EVENTS,
        help=f"Number of single-muon events. Default: {DEFAULT_NUM_EVENTS}.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=DEFAULT_SEED,
        help=f"Random seed. Default: {DEFAULT_SEED}.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    if args.num_events <= 0:
        raise ValueError("num_events must be a positive integer")

    macros_dir = Path(__file__).resolve().parent
    repo_root = macros_dir.parent

    muon_mac_path = macros_dir / "muon.mac"
    output_mac_path = macros_dir / "random_muon_scan.mac"
    output_csv_path = macros_dir / "random_muon_scan_positions.csv"
    gdml_path = repo_root / "geometry" / "final.gdml"

    variables = load_gdml_variables(gdml_path)
    slab_half_xy_mm = variables["slab_half_xy"]
    template_lines, _, source_y, unit_scale_from_mm, unit = load_template_lines(muon_mac_path)
    slab_half_xy = slab_half_xy_mm * unit_scale_from_mm
    positions = build_random_positions(args.num_events, slab_half_xy, source_y, args.seed)

    output_lines = build_header_comments(len(positions), args.seed)
    output_lines.extend(template_lines)
    output_lines.extend(build_visualization_lines())
    for position in positions:
        output_lines.append(format_position_line(position, unit))
        output_lines.append("/run/beamOn 1")
    output_lines.append("/vis/viewer/set/autoRefresh true")
    output_lines.append("/vis/viewer/refresh")

    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=output_mac_path.parent, delete=False
    ) as handle:
        handle.write("\n".join(output_lines) + "\n")
        temp_path = Path(handle.name)
    temp_path.replace(output_mac_path)

    write_positions_csv(output_csv_path, positions, unit)

    print(
        f"Wrote {len(positions)} random single-muon events to {output_mac_path} "
        f"with seed {args.seed}; truth labels: {output_csv_path}"
    )


if __name__ == "__main__":
    main()
